# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 21:28
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('menu', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2016, 5, 10, 21, 28, 47, 923546))),
                ('modified_date', models.DateTimeField()),
                ('order', models.IntegerField(default=0)),
                ('text', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
